name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: |
          ./gradlew build -x test -x checkstyleMain -x checkstyleTest -x verifyGoogleJavaFormat

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DRIVER=com.mysql.cj.jdbc.Driver" >> $GITHUB_ENV
          echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> $GITHUB_ENV
          echo "VERIFY_EMAIL_ENABLED=true" >> $GITHUB_ENV
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> $GITHUB_ENV
          echo "MAIL_PORT=587" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "RESET_PASSWORD_URL=${{ secrets.RESET_PASSWORD }}" >> $GITHUB_ENV
          echo "VERIFICATION_EMAIL_URL=${{ secrets.VERIFICATION_EMAIL_URL }}" >> $GITHUB_ENV
          echo "VERIFICATION_EMAIL_SENDER=${{ secrets.VERIFICATION_EMAIL_SENDER }}" >> $GITHUB_ENV
          echo "VERIFICATION_EMAIL_SUBJECT=${{ secrets.VERIFICATION_EMAIL_SUBJECT }}" >> $GITHUB_ENV
          echo "RESEND_VERIFICATION_EMAIL_SUBJECT=${{ secrets.RESEND_VERIFICATION_EMAIL_SUBJECT }}" >> $GITHUB_ENV
          echo "RESET_PASSWORD_EMAIL_SUBJECT=${{ secrets.RESET_PASSWORD_EMAIL_SUBJECT }}" >> $GITHUB_ENV
          echo "VERIFICATION_EMAIL_TEMPLATE_FILEPATH=${{ secrets.VERIFICATION_EMAIL_TEMPLATE_FILEPATH }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          ./gradlew test -i

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest